### ISSUE TITLE
Add RSS Feed

### ISSUE THREAD

**Issue by vinkla** [vinkla/vinkla.github.io#2]
RSS feed requested in https://twitter.com/freekmurze/status/628161553792126976 I'll add this asap.

**Comment by vinkla** [comment]
Done https://vinkla.com/feed.xml

**Comment by freekmurze** [comment]
Nice! Don't forget to add a link tag to all your pages, so rss readers can find the feed automatically.

**Comment by vinkla** [comment]
How do I do that?

**Comment by freekmurze** [comment]
Yep, that's the way to do it. The href-attribute should point to https://vinkla.com/feed.xml.

**Comment by vinkla** [comment]
Okay done fb6993612d4363e3c32b2a335a27d4560804f519
